BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DS_POC_CUSTOMERS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DS_POC_CUSTOMERS (
  ID NUMBER(19) NOT NULL,
  EMAIL VARCHAR2(255 CHAR) NOT NULL,
  DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
  ACTIVE NUMBER(1) NOT NULL,
  CREDIT NUMBER(12,2) NOT NULL,
  NOTES CLOB NULL,
  REGISTERED_AT TIMESTAMP(6) NOT NULL,
  UPDATED_AT TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_DS_POC_CUSTOMERS PRIMARY KEY (ID)
);
