WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING OFF FEEDBACK OFF PAGESIZE 0
SELECT COUNT(*) FROM DS_POC_CUSTOMERS;
SELECT ID || '|' || EMAIL || '|' || DISPLAY_NAME || '|' || TO_CHAR(CREDIT, 'FM9999999990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
FROM DS_POC_CUSTOMERS
ORDER BY ID;
